using UnityEngine;
using System.Collections;

public class CameraFixedAspectRatio : MonoBehaviour {
  int previousWidth;
  int previousHeight;

  const float targetaspect = 16.0f / 9.0f;

  void Start() {
    FixAspect();
  }

  void Update() {
    if (previousWidth != Screen.width || previousHeight != Screen.height) {
      previousWidth = Screen.width;
      previousHeight = Screen.height;
      FixAspect();
    }
  }

  void FixAspect() {
    float windowaspect = (float)Screen.width / (float)Screen.height;
    float scaleheight = windowaspect / targetaspect;
    Camera camera = GetComponent<Camera>();
    if (scaleheight < 1.0f) {
      Rect rect = camera.rect;
      rect.width = 1.0f;
      rect.height = scaleheight;
      rect.x = 0;
      rect.y = (1.0f - scaleheight) / 2.0f;
      camera.rect = rect;
    } else {
      float scalewidth = 1.0f / scaleheight;
      Rect rect = camera.rect;
      rect.width = scalewidth;
      rect.height = 1.0f;
      rect.x = (1.0f - scalewidth) / 2.0f;
      rect.y = 0;
      camera.rect = rect;
    }
  }
}
